apiVersion: v1
kind: Secret
metadata:
  name: gigaflow-secrets
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://gigaflow:password@postgres:5432/sentiment_db"
  minio-access-key: "minioadmin"
  minio-secret-key: "minioadmin"
  postgres-user: "gigaflow"
  postgres-password: "password"
  grafana-admin-password: "admin"
